# Sakura Hashimoto(003186429)
import random

MOTIVATIONAL_QUOTES = [
    "Your focus determines your reality. - George Lucas",
    "Discipline is remembering what you want.",
    "Focus on one small thing.",
    "Where focus goes, energy flows. - Tony Robbins",
    "The key is not to prioritize what's on your schedule, but to schedule your priorities. - Stephen Covey",
    "Concentration is the secret of strength in politics, in war, in trade, in short, in all management of human affairs. - Ralph Waldo Emerson",
    "Choose the hard right over the easy wrong.",
    "Things which matter most must never be at the mercy of things which matter least. - Johann Wolfgang von Goethe",
    "Simplicity is the ultimate sophistication. - Leonardo da Vinci",
    "You can't depend on your eyes when your imagination is out of focus. - Mark Twain",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "Only one thing matters: Focus on what you're doing right now.",
    "To be successful, the first thing to do is fall in love with your work. - Sister Mary Lauretta",
    "The power of concentration is the only key to the treasure-house of knowledge. - Swami Vivekananda",
    "Energy and persistence conquer all things. - Benjamin Franklin",
    "The trouble is, you think you have time. - Buddha",
    "The greatest weapon against stress is our ability to choose one thought over another. - William James",
    "Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort. - Paul J. Meyer",
    "The mind is everything. What you think you become. - Buddha",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Fall seven times, stand up eight. - Japanese Proverb",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "The difference between ordinary and extraordinary is that little extra.",
    "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. - Thomas Edison",
    "Great things are done by a series of small things brought together. - Vincent Van Gogh",
    "Continuous effort—not strength or intelligence—is the key to unlocking our potential. - Winston Churchill",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. - Dale Carnegie",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Progress, not perfection.",
    "I haven't failed. I've just found 10,000 ways that won't work. - Thomas Edison",
    "Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
    "You are what you repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
    "It's hard to beat a person who never gives up. - Babe Ruth",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Procrastination is the thief of time. - Edward Young",
    "The key is not spending time, but investing it. - Stephen Covey",
    "Do the hard jobs first. The easy jobs will take care of themselves. - Dale Carnegie",
    "Take care of the minutes and the hours will take care of themselves. - Lord Chesterfield",
    "The best preparation for good work tomorrow is to do good work today.",
    "Planning is bringing the future into the present so that you can do something about it now. - Alan Lakein",
    "Don't count the days, make the days count. - Muhammad Ali",
    "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
    "The purpose of our lives is to be happy and useful.",
    "Yesterday is not ours to recover, but tomorrow is ours to win or lose. - Lyndon B. Johnson",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Henry David Thoreau",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
    "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford",
    "Nothing is impossible, the word itself says 'I'm possible'! - Audrey Hepburn",
    "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
    "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand. - Vince Lombardi",
    "If it's important to you, you will find a way. If not, you'll find an excuse.",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Setting goals is the first step in turning the invisible into the visible. - Tony Robbins",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Your biggest challenge is not someone else. It's the voice in your head.",
    "Be brave enough to suck at something new.",
    "The man who moves a mountain begins by carrying away small stones. - Confucius",
    "You are built for this.",
    "Don't wait. The time will never be just right. - Napoleon Hill",
]


def get_random_quote():
    return random.choice(MOTIVATIONAL_QUOTES)
